# Generated by Django 3.0.6 on 2020-05-30 02:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(verbose_name='published date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogposts.Post')),
            ],
        ),
    ]
