# Generated by Django 3.0.6 on 2020-05-30 04:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0003_auto_20200530_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=None),
        ),
    ]
